version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1
    ports:
      - 2181:2181
      - 9998:8080 

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092-9093:9092-9093

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: development_minio_key
      MINIO_ROOT_PASSWORD: development_minio_secret
    command: server /export --console-address ":9001"
    ports:
      - 9002:9000
      - 9001:9001
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:12.1
    shm_size: 1G
    environment:
      POSTGRES_DB: intranet
      POSTGRES_USER: intranet
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/blogs
    restart: always
    ports:
      - 55435:5432

  elasticsearch:
    # image: elasticsearch:7.17.1
    build:
      context:  elasticsearch/
      dockerfile: Dockerfile
      args:
        ELK_VERSION: 7.17.1
#    volumes:
#      - ./docker/data:/usr/share/elasticsearch/data
#      - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx5g -Xms5g"

  # kibana:
  #   build:
  #     context: kibana/
  #     args:
  #       ELK_VERSION: 7.8.0
  #   restart: always
  #   volumes:
  #     - ./kibana/config/:/usr/share/kibana/config:ro
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
